### ISSUE TITLE
Line breaks?

### ISSUE THREAD

**Issue by michaelybecker** [JohnAlbin/UnityReadme#1]
Hi! Love your Unity package - makes life that much easier when jumpstarting new projects. Is there any way to do line breaks in the Text field? `\n` didn't work (is this a YAML format thing?) and, more expectedly, neither does hitting enter. Could these be text boxes, perhaps? I'm going to tinker with the .asset myself but figured you'd probably know the answer. Thanks!

**Comment by conath** [comment]
You can add line breaks by surrounding your text with `"` (quotation marks) and adding `\n` where you want the line break.

For example:

```yaml
  - heading: About this Project
    text: "This project contains the Unity C# Client.\n
	  Please get the latest release package from GitHub."
    linkText: Get the latest package from GitHub
    url: https://github.com/JohnAlbin/UnityReadme/releases
```

Produces in the Inspector:

![Screenshot 2021-11-29 010558](https://user-images.githubusercontent.com/12073163/143791891-cc44c0fa-ec81-4fe4-a413-df5858fe57e8.jpg)
